### ISSUE TITLE
Bug - Longest Streak

### ISSUE THREAD

**Issue by harshasrinivas** [arkon/github-streak#1]
![streak](https://cloud.githubusercontent.com/assets/7846363/16540840/f6be6208-408f-11e6-8298-047ca7161bfd.png)

The `longestStreak` variable isn't being updated once it reaches the end of the [loop](https://github.com/arkon/github-streak/blob/master/src/streak.js)

**Comment by arkon** [comment]
You're right! Fixed via 54d4e3e0027404cdd9b760fa8a398e12c596abde
